### PR TITLE
Some personalization functions

### PR DESCRIPTION
**Pull request by Vitu2002**
Well, I noticed that the api is a bit limited in terms of customization and translation, so I added the "Options" parameter, which accepts changes in message order, title, description and date customization.

### CODE REVIEW

**Comment by Ghosterzz** [comment]
Nice! I will test this change later on?

**Comment by Ghosterzz** [comment]
i have fixed some errors but:
if (options.inverseArray) messageCollection = messageCollection.reverse();
                                                                                          ^
TypeError: messageCollection.reverse is not a function
do you know how to fix this

**Comment by Vitu2002** [comment]
> i have fixed some errors but: if (options.inverseArray) messageCollection = messageCollection.reverse(); ^ TypeError: messageCollection.reverse is not a function do you know how to fix this


I don't know why this is having this problem, in my thoughts was for the "messageCollection" to be an array, but what if we tried to force a direct conversion to an array? something like that:
```js
// ...

const forcedArray = [];
await messageCollection.forEach(data => forcedArray.push(data))

if (options.inverseArray) messageCollection = forcedArray.reverse()

// ...

```

**Comment by Ghosterzz** [comment]
yes the ForcedArray worked

**Pull request closed without merging**
